# Generated by Django 3.0.6 on 2020-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='approved',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('O', 'outgoing'), ('R', 'rejected')], default='rejected', max_length=100),
            preserve_default=False,
        ),
    ]
