# Generated by Django 3.0.6 on 2020-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200606_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('O', 'Outgoing')], max_length=2),
        ),
    ]
